[package]
name = "VM_Translator"
version = "0.1.0"
authors = ["brs"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
